-- Schema only from the expenses-branch v2 installed before the engine branch.
-- No player data is included.
CREATE TABLE `ARTWORK` (`id` TEXT NOT NULL, `resource_name` TEXT NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE `EFFORT_LEVEL` (`id` TEXT NOT NULL, `label` TEXT NOT NULL, `fatigue_delta` INTEGER NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE `EXPENSE` (`event_id` TEXT NOT NULL, `blocking` INTEGER NOT NULL, `background_artwork_id` TEXT NOT NULL, `category_label` TEXT NOT NULL, `footer` TEXT NOT NULL, PRIMARY KEY(`event_id`), FOREIGN KEY(`event_id`) REFERENCES `EVENT`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`background_artwork_id`) REFERENCES `ARTWORK`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `EXPENSE_CHOICE_RULE` (`choice_id` TEXT NOT NULL, `kind` TEXT NOT NULL, `effort_level_id` TEXT, PRIMARY KEY(`choice_id`), FOREIGN KEY(`choice_id`) REFERENCES `EVENT_CHOICE`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`effort_level_id`) REFERENCES `EFFORT_LEVEL`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `EVENT_ARTWORK_LAYER` (`event_id` TEXT NOT NULL, `position` INTEGER NOT NULL, `artwork_id` TEXT NOT NULL, `x` REAL NOT NULL, `y` REAL NOT NULL, `width` REAL NOT NULL, `height` REAL NOT NULL, PRIMARY KEY(`event_id`, `position`), FOREIGN KEY(`event_id`) REFERENCES `EVENT`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`artwork_id`) REFERENCES `ARTWORK`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `GOAL` (`id` TEXT NOT NULL, `title` TEXT NOT NULL, `description` TEXT NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE `ITEM` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `description` TEXT NOT NULL, PRIMARY KEY(`id`));
CREATE TABLE `CHAPTER` (`id` TEXT NOT NULL, `title` TEXT NOT NULL, `goal_id` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`goal_id`) REFERENCES `GOAL`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `GAME_DAY` (`id` TEXT NOT NULL, `chapter_id` TEXT NOT NULL, `day_number` INTEGER NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`chapter_id`) REFERENCES `CHAPTER`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `EVENT` (`id` TEXT NOT NULL, `type` TEXT NOT NULL, `title` TEXT NOT NULL, `description` TEXT NOT NULL, `min_satiety` INTEGER, `max_fatigue` INTEGER, `pet_state_on_start` TEXT, `money_delta_on_start` INTEGER NOT NULL, `budget_section_on_start` TEXT, `next_chapter_id` TEXT, PRIMARY KEY(`id`), FOREIGN KEY(`next_chapter_id`) REFERENCES `CHAPTER`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `DAY_EVENT` (`id` TEXT NOT NULL, `day_id` TEXT NOT NULL, `position` INTEGER NOT NULL, `event_id` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`day_id`) REFERENCES `GAME_DAY`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`event_id`) REFERENCES `EVENT`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `EVENT_CHOICE` (`id` TEXT NOT NULL, `event_id` TEXT NOT NULL, `position` INTEGER NOT NULL, `text` TEXT NOT NULL, `money_delta` INTEGER NOT NULL, `budget_section` TEXT, `pet_state_after` TEXT, `goal_impact` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`event_id`) REFERENCES `EVENT`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `GOAL_REQUIRED_ITEM` (`goal_id` TEXT NOT NULL, `item_id` TEXT NOT NULL, PRIMARY KEY(`goal_id`, `item_id`), FOREIGN KEY(`goal_id`) REFERENCES `GOAL`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`item_id`) REFERENCES `ITEM`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `EVENT_ITEM_EFFECT` (`id` TEXT NOT NULL, `event_id` TEXT NOT NULL, `position` INTEGER NOT NULL, `item_id` TEXT NOT NULL, `operation` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`event_id`) REFERENCES `EVENT`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`item_id`) REFERENCES `ITEM`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `CHOICE_ITEM_EFFECT` (`id` TEXT NOT NULL, `choice_id` TEXT NOT NULL, `position` INTEGER NOT NULL, `item_id` TEXT NOT NULL, `operation` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`choice_id`) REFERENCES `EVENT_CHOICE`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`item_id`) REFERENCES `ITEM`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `GAME_STATE` (`id` TEXT NOT NULL, `visual_state` TEXT NOT NULL, `selected_look` TEXT NOT NULL, `satiety` INTEGER NOT NULL, `fatigue` INTEGER NOT NULL, `balance` INTEGER NOT NULL, `planned_needs` INTEGER NOT NULL, `planned_wants` INTEGER NOT NULL, `planned_savings` INTEGER NOT NULL, `planned_reserve` INTEGER NOT NULL, `current_day_id` TEXT, `next_script_position` INTEGER, `active_event_id` TEXT, `expense_sequence` INTEGER NOT NULL DEFAULT 0, `expense_stage` TEXT NOT NULL DEFAULT 'CHOOSING', `earning_attempt` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(`id`), FOREIGN KEY(`current_day_id`) REFERENCES `GAME_DAY`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`current_day_id`, `next_script_position`) REFERENCES `DAY_EVENT`(`day_id`, `position`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`active_event_id`) REFERENCES `EVENT`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `PLAYER_DECISION` (`id` TEXT NOT NULL, `game_state_id` TEXT NOT NULL, `position` INTEGER NOT NULL, `choice_id` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`game_state_id`) REFERENCES `GAME_STATE`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`choice_id`) REFERENCES `EVENT_CHOICE`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE `OWNED_ITEM` (`id` TEXT NOT NULL, `game_state_id` TEXT NOT NULL, `position` INTEGER NOT NULL, `item_id` TEXT NOT NULL, PRIMARY KEY(`id`), FOREIGN KEY(`game_state_id`) REFERENCES `GAME_STATE`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION , FOREIGN KEY(`item_id`) REFERENCES `ITEM`(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION );
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
CREATE INDEX `index_EXPENSE_background_artwork_id` ON `EXPENSE` (`background_artwork_id`);
CREATE INDEX `index_EXPENSE_CHOICE_RULE_effort_level_id` ON `EXPENSE_CHOICE_RULE` (`effort_level_id`);
CREATE INDEX `index_EVENT_ARTWORK_LAYER_artwork_id` ON `EVENT_ARTWORK_LAYER` (`artwork_id`);
CREATE INDEX `index_CHAPTER_goal_id` ON `CHAPTER` (`goal_id`);
CREATE INDEX `index_GAME_DAY_chapter_id` ON `GAME_DAY` (`chapter_id`);
CREATE INDEX `index_EVENT_next_chapter_id` ON `EVENT` (`next_chapter_id`);
CREATE UNIQUE INDEX `index_DAY_EVENT_day_id_position` ON `DAY_EVENT` (`day_id`, `position`);
CREATE INDEX `index_DAY_EVENT_event_id` ON `DAY_EVENT` (`event_id`);
CREATE UNIQUE INDEX `index_EVENT_CHOICE_event_id_position` ON `EVENT_CHOICE` (`event_id`, `position`);
CREATE INDEX `index_GOAL_REQUIRED_ITEM_item_id` ON `GOAL_REQUIRED_ITEM` (`item_id`);
CREATE UNIQUE INDEX `index_EVENT_ITEM_EFFECT_event_id_position` ON `EVENT_ITEM_EFFECT` (`event_id`, `position`);
CREATE INDEX `index_EVENT_ITEM_EFFECT_item_id` ON `EVENT_ITEM_EFFECT` (`item_id`);
CREATE UNIQUE INDEX `index_CHOICE_ITEM_EFFECT_choice_id_position` ON `CHOICE_ITEM_EFFECT` (`choice_id`, `position`);
CREATE INDEX `index_CHOICE_ITEM_EFFECT_item_id` ON `CHOICE_ITEM_EFFECT` (`item_id`);
CREATE INDEX `index_GAME_STATE_current_day_id` ON `GAME_STATE` (`current_day_id`);
CREATE INDEX `index_GAME_STATE_current_day_id_next_script_position` ON `GAME_STATE` (`current_day_id`, `next_script_position`);
CREATE INDEX `index_GAME_STATE_active_event_id` ON `GAME_STATE` (`active_event_id`);
CREATE UNIQUE INDEX `index_PLAYER_DECISION_game_state_id_position` ON `PLAYER_DECISION` (`game_state_id`, `position`);
CREATE INDEX `index_PLAYER_DECISION_choice_id` ON `PLAYER_DECISION` (`choice_id`);
CREATE UNIQUE INDEX `index_OWNED_ITEM_game_state_id_position` ON `OWNED_ITEM` (`game_state_id`, `position`);
CREATE INDEX `index_OWNED_ITEM_item_id` ON `OWNED_ITEM` (`item_id`);
INSERT INTO room_master_table VALUES (42, '60def24db827a0073f78e5218e023b32');
PRAGMA user_version = 2;
