package ru.nksk.lctapp.core.ui.media

/** Paths are relative to AssetManager; metadata resolution never starts playback. */
internal const val INTRO_VIDEO_ASSET = "media/video/intro_fox.mp4"

internal object BundledMediaCatalog {
    fun assetPath(cueKey: String): String? = assets[cueKey]

    private val assets = mapOf(
        "ambient.butcher_shop" to "media/audio/ambient_butcher_shop.mp3",
        "ambient.port" to "media/audio/ambient_port.mp3",
        "narration.story.blank_region" to "media/audio/narration_story_blank_region.mp3",
        "narration.story.border_beacon" to "media/audio/narration_story_border_beacon.mp3",
        "narration.story.calibration_station" to "media/audio/narration_story_calibration_station.mp3",
        "narration.story.cargo_journal" to "media/audio/narration_story_cargo_journal.mp3",
        "narration.story.cellar_crate" to "media/audio/narration_story_cellar_crate.mp3",
        "narration.story.central_hub" to "media/audio/narration_story_central_hub.mp3",
        "narration.story.change_one" to "media/audio/narration_story_change_one.mp3",
        "narration.story.chronoscope_part" to "media/audio/narration_story_chronoscope_part.mp3",
        "narration.story.closed_bridge" to "media/audio/narration_story_closed_bridge.mp3",
        "narration.story.coastal_fragment" to "media/audio/narration_story_coastal_fragment.mp3",
        "narration.story.crate_mark" to "media/audio/narration_story_crate_mark.mp3",
        "narration.story.duty_room" to "media/audio/narration_story_duty_room.mp3",
        "narration.story.first_route" to "media/audio/narration_story_first_route.mp3",
        "narration.story.forest_stone" to "media/audio/narration_story_forest_stone.mp3",
        "narration.story.fork_symbol" to "media/audio/narration_story_fork_symbol.mp3",
        "narration.story.great_expedition" to "media/audio/narration_story_great_expedition.mp3",
        "narration.story.hall_of_paths" to "media/audio/narration_story_hall_of_paths.mp3",
        "narration.story.house_base" to "media/audio/narration_story_house_base.mp3",
        "narration.story.keeper_seal" to "media/audio/narration_story_keeper_seal.mp3",
        "narration.story.kingdom_map" to "media/audio/narration_story_kingdom_map.mp3",
        "narration.story.last_keeper_message" to "media/audio/narration_story_last_keeper_message.mp3",
        "narration.story.last_relay" to "media/audio/narration_story_last_relay.mp3",
        "narration.story.last_station" to "media/audio/narration_story_last_station.mp3",
        "narration.story.last_tower_cargo" to "media/audio/narration_story_last_tower_cargo.mp3",
        "narration.story.luna_damaged_map" to "media/audio/narration_story_luna_damaged_map.mp3",
        "narration.story.luna_note" to "media/audio/narration_story_luna_note.mp3",
        "narration.story.map_table" to "media/audio/narration_story_map_table.mp3",
        "narration.story.marked_plate" to "media/audio/narration_story_marked_plate.mp3",
        "narration.story.missing_road" to "media/audio/narration_story_missing_road.mp3",
        "narration.story.mountain_sign" to "media/audio/narration_story_mountain_sign.mp3",
        "narration.story.network_lights" to "media/audio/narration_story_network_lights.mp3",
        "narration.story.network_shutdown" to "media/audio/narration_story_network_shutdown.mp3",
        "narration.story.new_map" to "media/audio/narration_story_new_map.mp3",
        "narration.story.night_observation" to "media/audio/narration_story_night_observation.mp3",
        "narration.story.not_prediction" to "media/audio/narration_story_not_prediction.mp3",
        "narration.story.observation_network" to "media/audio/narration_story_observation_network.mp3",
        "narration.story.observatory_receiver" to "media/audio/narration_story_observatory_receiver.mp3",
        "narration.story.old_map" to "media/audio/narration_story_old_map.mp3",
        "narration.story.quiet_tower_expedition" to "media/audio/narration_story_quiet_tower_expedition.mp3",
        "narration.story.recent_repairs" to "media/audio/narration_story_recent_repairs.mp3",
        "narration.story.relay_station" to "media/audio/narration_story_relay_station.mp3",
        "narration.story.researcher_house" to "media/audio/narration_story_researcher_house.mp3",
        "narration.story.return_code" to "media/audio/narration_story_return_code.mp3",
        "narration.story.route_archive" to "media/audio/narration_story_route_archive.mp3",
        "narration.story.route_comparison" to "media/audio/narration_story_route_comparison.mp3",
        "narration.story.route_token" to "media/audio/narration_story_route_token.mp3",
        "narration.story.second_path_scroll" to "media/audio/narration_story_second_path_scroll.mp3",
        "narration.story.service_emblem" to "media/audio/narration_story_service_emblem.mp3",
        "narration.story.signal_post" to "media/audio/narration_story_signal_post.mp3",
        "narration.story.stone_post" to "media/audio/narration_story_stone_post.mp3",
        "narration.story.storm_shelter" to "media/audio/narration_story_storm_shelter.mp3",
        "narration.story.telescope_journal" to "media/audio/narration_story_telescope_journal.mp3",
        "narration.story.tester" to "media/audio/narration_story_tester.mp3",
        "narration.story.three_answers" to "media/audio/narration_story_three_answers.mp3",
        "narration.story.three_lenses" to "media/audio/narration_story_three_lenses.mp3",
        "narration.story.three_lights" to "media/audio/narration_story_three_lights.mp3",
        "narration.story.tiko_arrives" to "media/audio/narration_story_tiko_arrives.mp3",
        "narration.story.tower_reply" to "media/audio/narration_story_tower_reply.mp3",
        "narration.story.unsigned_letter" to "media/audio/narration_story_unsigned_letter.mp3",
        "narration.story.workshop_photo" to "media/audio/narration_story_workshop_photo.mp3",
        "narration.unexpected.backpack_strap" to "media/audio/narration_unexpected_frayed_rope.mp3",
        "narration.unexpected.bent_frame" to "media/audio/narration_unexpected_bent_key.mp3",
        "narration.unexpected.bent_key" to "media/audio/narration_unexpected_bent_key.mp3",
        "narration.unexpected.broken_window" to "media/audio/narration_unexpected_broken_window.mp3",
        "narration.unexpected.cloudy_lens" to "media/audio/narration_unexpected_cloudy_lens.mp3",
        "narration.unexpected.fragile_scroll" to "media/audio/narration_unexpected_unbound_journal.mp3",
        "narration.unexpected.frayed_rope" to "media/audio/narration_unexpected_frayed_rope.mp3",
        "narration.unexpected.jammed_crate" to "media/audio/narration_unexpected_jammed_crate.mp3",
        "narration.unexpected.lantern_broken" to "media/audio/narration_unexpected_lantern_broken.mp3",
        "narration.unexpected.leaking_roof" to "media/audio/narration_unexpected_leaking_roof.mp3",
        "narration.unexpected.loose_tripod" to "media/audio/narration_unexpected_workbench_support.mp3",
        "narration.unexpected.missing_gear_tooth" to "media/audio/narration_unexpected_missing_gear_tooth.mp3",
        "narration.unexpected.resin_backpack" to "media/audio/narration_unexpected_resin_backpack.mp3",
        "narration.unexpected.scratched_plate" to "media/audio/narration_unexpected_cloudy_lens.mp3",
        "narration.unexpected.smoky_lantern" to "media/audio/narration_unexpected_tilted_roof_lens.mp3",
        "narration.unexpected.stomach_ache" to "media/audio/narration_unexpected_stomach_ache.mp3",
        "narration.unexpected.stuck_compass" to "media/audio/narration_unexpected_stuck_ring.mp3",
        "narration.unexpected.stuck_lever" to "media/audio/narration_unexpected_stuck_lever.mp3",
        "narration.unexpected.stuck_ring" to "media/audio/narration_unexpected_stuck_ring.mp3",
        "narration.unexpected.tarnished_plate" to "media/audio/narration_unexpected_tarnished_plate.mp3",
        "narration.unexpected.tilted_roof_lens" to "media/audio/narration_unexpected_tilted_roof_lens.mp3",
        "narration.unexpected.unbound_journal" to "media/audio/narration_unexpected_unbound_journal.mp3",
        "narration.unexpected.wet_map" to "media/audio/narration_unexpected_unbound_journal.mp3",
        "narration.unexpected.wheel_cracked" to "media/audio/narration_unexpected_workbench_support.mp3",
        "narration.unexpected.workbench_support" to "media/audio/narration_unexpected_workbench_support.mp3",
        "sound.payment" to "media/audio/sound_payment.mp3",
        "sound.purchase_appears" to "media/audio/sound_purchase_appears.mp3",
        "sound.telescope_adjustment" to "media/audio/sound_telescope_adjustment.mp3",
        "story.chapter_1" to "media/audio/story_chapter_1.mp3",
        "story.chapter_2" to "media/audio/story_chapter_2.mp3",
        "story.chapter_3" to "media/audio/story_chapter_3.mp3",
        "story.chapter_4" to "media/audio/story_chapter_4.mp3",
        "story.chapter_5" to "media/audio/story_chapter_5.mp3",
    )
}
